site_name: AFC-Klipper-Add-On Documentation
site_description: "A guide to the AFC Klipper Add-On Software"
site_url: https://armoredturtle.xyz/docs/
repo_url: https://github.com/ArmoredTurtle/AFC-Klipper-Add-On
edit_uri: 'blob/dev-docs/documentation/'
repo_name: ArmoredTurtle/AFC-Klipper-Add-On
use_directory_urls: False
docs_dir: '../'
site_dir: '../../site/'

nav:
  - Home:
    - Overview: index.md
    - Features: features.md
  - Installation / Getting Started:
    - Quick Start: installation/quick-start.md
    - Installation:
        - Getting Started: installation/getting-started.md
        - Runtime Options: installation/runtime-options.md
        - Installation Menus:
          - Main Menu: installation/main-menu.md
          - Install Menu: installation/install-menu.md
          - Utilities Menu: installation/utilities-menu.md
        - Uninstall Process: installation/uninstall-process.md
    - Calibration Process: installation/calibration.md
    - Buffer Overview: installation/buffer-overview.md
    - Buffer Ram Sensor: installation/buffer-ram-sensor.md
  - Configuration:
    - Configuration Overview: configuration/configuration_overview.md
    - Configuration Files:
        - AFC.cfg: configuration/AFC.cfg.md
        - AFC_Hardware.cfg: configuration/AFC_Hardware.cfg.md
        - AFC_UnitType_1.cfg: configuration/AFC_UnitType_1.cfg.md
        - AFC_Macro_Vars.cfg: configuration/AFC_Macro_Vars.cfg.md
    - Configuration Examples: configuration/configuration_examples.md
  - Commands:
      - Macros:
          - Macro Overview: klipper/macros.md
          - Internal Macros:
              - Spool Macros: klipper/internal/spool.md
              - Calibration Macros: klipper/internal/calibration.md
              - Tip Forming Macros: klipper/internal/tip_forming.md
              - Buffer Macros: klipper/internal/buffer.md
              - Lane / Movement Macros: klipper/internal/lane.md
              - Misc. Macros: klipper/internal/misc.md
          - External Macros: klipper/external/macros.md
  - Troubleshooting:
    - Troubleshooting: troubleshooting/troubleshooting.md
    - FAQ: troubleshooting/faq.md
  - BoxTurtle:
      - Overview: boxturtle/index.md
      - Initial Startup: boxturtle/initial-startup.md
      - LDO Kit Errata: boxturtle/errata.md
      - BOM: boxturtle/bom.md
      - Wiring Guide: boxturtle/wiring-guide.md
  - Assembly Manual: https://armoredturtle.xyz

draft_docs: |
  _afc/README.md
  _unpublished.md 

theme:
  icon:
    repo: fontawesome/brands/github
  name: material
  logo: assets/logo.png
#  palette:
#    - media: "(prefers-color-scheme)"
#      toggle:
#        icon: material/brightness-auto
#        name: Switch to light mode
#    - media: "(prefers-color-scheme: light)"
#      scheme: default
#      toggle:
#        icon: material/brightness-7
#        name: Switch to dark mode
#    - media: "(prefers-color-scheme: dark)"
#      scheme: slate
#      toggle:
#        icon: material/brightness-4
#        name: Switch to system preference
  primary: custom

  features:
    - content.code.copy
    - content.action.edit
    - content.action.view
    - search.suggest
    - search.highlight
    - search.share
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.expand
    - navigation.path
    - navigation.footer

plugins:
  - search:
      lang: en
  - mkdocs-simple-hooks:
      hooks:
        on_post_page: "mkdoc_hooks:post_page"
        #on_serve: "mkdocs_hooks:force_reload"
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          options:
            show_source: false
          paths: [../../extras/]


markdown_extensions:
- admonition
- attr_list
- md_in_html
- pymdownx.blocks.caption
- pymdownx.details
- pymdownx.tilde
- pymdownx.tabbed:
    alternate_style: true
- pymdownx.highlight:
    anchor_linenums: true
    line_spans: __span
    pygments_lang_class: true
- pymdownx.inlinehilite
- pymdownx.snippets
- pymdownx.superfences:
    custom_fences:
      - name: mermaid
        class: mermaid
        format: !!python/name:pymdownx.superfences.fence_code_format
- codehilite
- toc:
    permalink: true

extra_css:
  - stylesheets/extra.css

extra:
  consent:
    title: Cookie consent
    description: >- 
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.

copyright: >
  Copyright &copy; 2024 - 2025 Armored Turtle –
  <a href="#__consent">Change cookie settings</a>